#############################################################################
# Makefile for building: stockona
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Jan 14 22:15:52 2013
# Project:  stockona.pro
# Template: app
# Command: c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile stockona.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVER="\"0.6.6\"" -DQ_WS_HARMATTAN -DHARMATTAN_BOOSTER -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -D_FILE_OFFSET_BITS=64 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe `pkg-config --cflags qdeclarative-boostable` -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -Wno-psabi -D_FILE_OFFSET_BITS=64 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSql -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtLocation -Icomponent -Iqmlapplicationviewer -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = `pkg-config --libs qdeclarative-boostable` -pie -rdynamic -Wl,-O1 -Wl,-rpath,C:/usr/lib
LIBS          = $(SUBLIBS)  -LC:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -lssl -lcrypto -laegis_crypto -lcreds -lbb5 -L/usr/lib -lQtLocation -lQtDeclarative -lQtSql -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = c:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = component/requestqueue.cpp \
		component/adinterface.cpp \
		component/inneractiveplugin.cpp \
		src/main.cpp \
		src/filehandler.cpp \
		src/loadhelper.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc/moc_requestqueue.cpp \
		moc/moc_adinterface.cpp \
		moc/moc_filehandler.cpp \
		moc/moc_loadhelper.cpp \
		moc/moc_qmlapplicationviewer.cpp
OBJECTS       = obj/requestqueue.o \
		obj/adinterface.o \
		obj/inneractiveplugin.o \
		obj/main.o \
		obj/filehandler.o \
		obj/loadhelper.o \
		obj/qmlapplicationviewer.o \
		obj/moc_requestqueue.o \
		obj/moc_adinterface.o \
		obj/moc_filehandler.o \
		obj/moc_loadhelper.o \
		obj/moc_qmlapplicationviewer.o
DIST          = ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		component/component.pri \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		stockona.pro
QMAKE_TARGET  = stockona
DESTDIR       = 
TARGET        = stockona

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: stockona.pro  ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		component/component.pri \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile stockona.pro
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
component/component.pri:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtSql.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
c:/QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile stockona.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/stockona0.6.6 || $(MKDIR) obj/stockona0.6.6 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/stockona0.6.6/ && $(COPY_FILE) --parents component/requestqueue.h component/adinterface.h component/inneractiveplugin.h src/filehandler.h src/loadhelper.h src/params.h qmlapplicationviewer/qmlapplicationviewer.h obj/stockona0.6.6/ && $(COPY_FILE) --parents component/requestqueue.cpp component/adinterface.cpp component/inneractiveplugin.cpp src/main.cpp src/filehandler.cpp src/loadhelper.cpp qmlapplicationviewer/qmlapplicationviewer.cpp obj/stockona0.6.6/ && $(COPY_FILE) --parents stockona_zh_TW.ts obj/stockona0.6.6/ && (cd `dirname obj/stockona0.6.6` && $(TAR) stockona0.6.6.tar stockona0.6.6 && $(COMPRESS) stockona0.6.6.tar) && $(MOVE) `dirname obj/stockona0.6.6`/stockona0.6.6.tar.gz . && $(DEL_FILE) -r obj/stockona0.6.6


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_requestqueue.cpp moc/moc_adinterface.cpp moc/moc_filehandler.cpp moc/moc_loadhelper.cpp moc/moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_requestqueue.cpp moc/moc_adinterface.cpp moc/moc_filehandler.cpp moc/moc_loadhelper.cpp moc/moc_qmlapplicationviewer.cpp
moc/moc_requestqueue.cpp: component/requestqueue.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) component/requestqueue.h -o moc/moc_requestqueue.cpp

moc/moc_adinterface.cpp: component/adinterface.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) component/adinterface.h -o moc/moc_adinterface.cpp

moc/moc_filehandler.cpp: src/params.h \
		src/filehandler.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/filehandler.h -o moc/moc_filehandler.cpp

moc/moc_loadhelper.cpp: src/loadhelper.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/loadhelper.h -o moc/moc_loadhelper.cpp

moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	C:/QtSDK/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc/moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/requestqueue.o: component/requestqueue.cpp component/requestqueue.h \
		component/adinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/requestqueue.o component/requestqueue.cpp

obj/adinterface.o: component/adinterface.cpp component/adinterface.h \
		component/requestqueue.h \
		component/cuseragent/cuseragent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/adinterface.o component/adinterface.cpp

obj/inneractiveplugin.o: component/inneractiveplugin.cpp component/inneractiveplugin.h \
		component/adinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/inneractiveplugin.o component/inneractiveplugin.cpp

obj/main.o: src/main.cpp src/fileHandler.h \
		src/params.h \
		src/loadhelper.h \
		component/inneractiveplugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/filehandler.o: src/filehandler.cpp src/filehandler.h \
		src/params.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/filehandler.o src/filehandler.cpp

obj/loadhelper.o: src/loadhelper.cpp src/loadhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/loadhelper.o src/loadhelper.cpp

obj/qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

obj/moc_requestqueue.o: moc/moc_requestqueue.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_requestqueue.o moc/moc_requestqueue.cpp

obj/moc_adinterface.o: moc/moc_adinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_adinterface.o moc/moc_adinterface.cpp

obj/moc_filehandler.o: moc/moc_filehandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_filehandler.o moc/moc_filehandler.cpp

obj/moc_loadhelper.o: moc/moc_loadhelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_loadhelper.o moc/moc_loadhelper.cpp

obj/moc_qmlapplicationviewer.o: moc/moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qmlapplicationviewer.o moc/moc_qmlapplicationviewer.cpp

####### Install

install_splash: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/qml/stockona/gfx/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/qml/stockona/gfx/ 
	-$(INSTALL_FILE) c:/stockona/stockona/images/stockona-splash.jpg $(INSTALL_ROOT)/opt/stockona/qml/stockona/gfx/


uninstall_splash:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/stockona/qml/stockona/gfx/stockona-splash.jpg
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/qml/stockona/gfx/ 


install_itemstockona_core: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/qml/ 
	-$(INSTALL_DIR) c:/stockona/stockona/qml/stockona/common/stockona $(INSTALL_ROOT)/opt/stockona/qml/


uninstall_itemstockona_core:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/stockona/qml/stockona
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/qml/ 


install_itemfolder_components: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/qml/stockona/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/qml/stockona/ 
	-$(INSTALL_DIR) c:/stockona/stockona/component/inneractive $(INSTALL_ROOT)/opt/stockona/qml/stockona/


uninstall_itemfolder_components:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/stockona/qml/stockona/inneractive
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/qml/stockona/ 


install_itemtrans_folder: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/ 
	-$(INSTALL_DIR) c:/stockona/stockona/i18n $(INSTALL_ROOT)/opt/stockona/


uninstall_itemtrans_folder:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/stockona/i18n
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/ 


install_itemplatform_qml: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/qml/ 
	-$(INSTALL_DIR) c:/stockona/stockona/qml/stockona/harmattan/stockona $(INSTALL_ROOT)/opt/stockona/qml/


uninstall_itemplatform_qml:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/stockona/qml/stockona
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/qml/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) c:/stockona/stockona/stockona80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/stockona80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) c:/stockona/stockona/stockona_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/stockona_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/stockona/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/stockona/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/stockona/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/stockona/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/stockona/bin/ 


install:  install_splash install_itemstockona_core install_itemfolder_components install_itemtrans_folder install_itemplatform_qml install_icon install_desktopfile install_target  FORCE

uninstall: uninstall_splash uninstall_itemstockona_core uninstall_itemfolder_components uninstall_itemtrans_folder uninstall_itemplatform_qml uninstall_icon uninstall_desktopfile uninstall_target   FORCE

FORCE:

